name: tech.decompiled.tpomatic.TPOmatic
version: '0.1'
main: tech.decompiled.tpomatic.TPOmatic
api-version: '1.14'

commands:
  tpify:
    description: "Teleports the command sender to a random location."
    usage: "/tpify"